sys_bank/config/routes.rb
Rails.application.routes.draw do
  resources :movement_accounts
  resources :agencies
  devise_for :users
  resources :accounts
  root to: "home#index"
  get "home/username"
  get "movement_accounts/index"
  get "accounts/index"
end

sys_bank/app/models/agency.rb
class Agency < ApplicationRecord
    has_many :accounts, class_name: 'Account'

    def agency_num_and_name
        num_agency + ' - ' + adress
    end
end

sys_bank/app/controllers/agencies_controller.rb
class AgenciesController < ApplicationController
  before_action :set_agency, only: %i[ show edit update destroy ]

  # GET /agencies or /agencies.json
  def index
    @agencies = Agency.all
  end

  # GET /agencies/1 or /agencies/1.json
  def show
  end

  # GET /agencies/new
  def new
    @agency = Agency.new
  end

  # GET /agencies/1/edit
  def edit
  end

  # POST /agencies or /agencies.json
  def create
    @agency = Agency.new(agency_params)

    respond_to do |format|
      if @agency.save
        format.html { redirect_to @agency, notice: "Agency was successfully created." }
        format.json { render :show, status: :created, location: @agency }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @agency.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /agencies/1 or /agencies/1.json
  def update
    respond_to do |format|
      if @agency.update(agency_params)
        format.html { redirect_to @agency, notice: "Agency was successfully updated." }
        format.json { render :show, status: :ok, location: @agency }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @agency.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /agencies/1 or /agencies/1.json
  def destroy
    @agency.destroy
    respond_to do |format|
      format.html { redirect_to agencies_url, notice: "Agency was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_agency
      @agency = Agency.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def agency_params
      params.require(:agency).permit(:num_agency, :adress)
    end
end

sys_bank/app/helpers/agencies_helper.rb
module AgenciesHelper
end

sys_bank/app/views/agencies/_form.html.erb
<%= form_with(model: agency, local: true) do |form| %>
  <% if agency.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(agency.errors.count, "error") %> prohibited this agency from being saved:</h2>

      <ul>
      <% agency.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :num_agency %>
    <%= form.text_field :num_agency %>
  </div>

  <div class="field">
    <%= form.label :adress %>
    <%= form.text_field :adress %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

sys_bank/app/views/agencies/edit.html.erb
<h1>Editing Agency</h1>

<%= render 'form', agency: @agency %>

<%= link_to 'Show', @agency %> |
<%= link_to 'Back', agencies_path %>

sys_bank/app/views/agencies/index.html.erb
<p id="notice"><%= notice %></p>
<div class="content">
  <div class="menu">
    <h1>Agencies</h1>

    <table>
      <thead>
        <tr>
          <th>Num agency</th>
          <th>Adress</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @agencies.each do |agency| %>
          <tr>
            <td><%= agency.num_agency %></td>
            <td><%= agency.adress %></td>
            <td><%= link_to 'Show', agency %></td>
            <td><%= link_to 'Edit', edit_agency_path(agency) %></td>
            <td><%= link_to 'Destroy', agency, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>

    <div class="link">
      <%= link_to 'New Agency', new_agency_path %>
      <%= link_to "Back", root_path %>
    </div>
  </div>
</div>

sys_bank/app/views/agencies/new.html.erb
<h1>New Agency</h1>

<%= render 'form', agency: @agency %>

<%= link_to 'Back', agencies_path %>

sys_bank/app/views/agencies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Num agency:</strong>
  <%= @agency.num_agency %>
</p>

<p>
  <strong>Adress:</strong>
  <%= @agency.adress %>
</p>

<%= link_to 'Edit', edit_agency_path(@agency) %> |
<%= link_to 'Back', agencies_path %>