sys_bank/config/routes.rb
Rails.application.routes.draw do
  resources :movement_accounts
  resources :agencies
  devise_for :users
  resources :accounts
  root to: "home#index"
  get "home/username"
  get "movement_accounts/index"
  get "accounts/index"
end

sys_bank/app/models/movement_account.rb
class MovementAccount < ApplicationRecord
    belongs_to :account, class_name: 'Account'
    belongs_to :account_destiny, class_name: 'Account', foreign_key: "account_destiny_id", optional: true
    belongs_to :user, class_name: 'User'

    validates :account_destiny_id, presence: true, if: :transfer?
    validate :users_transfer_validate, if: :transfer?
    validate :value_validate
    validates :value, presence: true

    enum movement_type:{
        bank_draft: 0,
        deposit: 1,
        reversal: 2,
        transfer: 3
    }

    def users_transfer_validate
        if self.account_id == self.account_destiny_id
            errors.add(:account_id, "can't same.")
        end
    end

    def value_validate
        if self.account.limit < self.value 
            errors.add(:value, "greater than limit.")
        end
    end

end

sys_bank/app/controllers/movement_accounts_controller.rb
class MovementAccountsController < ApplicationController
  before_action :set_movement_account, only: %i[ show edit update destroy ]

  # GET /movement_accounts or /movement_accounts.json
  def index
    @movement_accounts = MovementAccount.where(account_id: current_user.account.id).or(MovementAccount.where(account_destiny_id: current_user.account.id))
  end

  # GET /movement_accounts/1 or /movement_accounts/1.json
  def show
  end

  # GET /movement_accounts/new
  def new
    @movement_account = MovementAccount.new(movement_type: params[:movement_type])
  end

  # GET /movement_accounts/1/edit
  def edit
  end

  # POST /movement_accounts or /movement_accounts.json
  def create
    @movement_account = MovementAccount.new(movement_account_params)

    respond_to do |format|
      if @movement_account.save
        format.html { redirect_to @movement_account, notice: "Movement account was successfully created." }
        format.json { render :show, status: :created, location: @movement_account }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @movement_account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movement_accounts/1 or /movement_accounts/1.json
  def update
    respond_to do |format|
      if @movement_account.update(movement_account_params)
        format.html { redirect_to @movement_account, notice: "Movement account was successfully updated." }
        format.json { render :show, status: :ok, location: @movement_account }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @movement_account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movement_accounts/1 or /movement_accounts/1.json
  def destroy
    @movement_account.destroy
    respond_to do |format|
      format.html { redirect_to movement_accounts_url, notice: "Movement account was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movement_account
      @movement_account = MovementAccount.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def movement_account_params
      params.require(:movement_account).permit(:movement_date, :value, :account_id, :user_id, :movement_type, :account_destiny_id)
    end
end

sys_bank/app/helpers/movement_accounts_helper.rb
module MovementAccountsHelper
    
end

sys_bank/app/views/movement_accounts/_form.html.erb
<%= form_with(model: movement_account, local: true) do |form| %>
  <% if movement_account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(movement_account.errors.count, "error") %> prohibited this movement_account from being saved:</h2>

      <ul>
      <% movement_account.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.hidden_field :user_id, value: current_user.id %>
  </div>

  <div class="field">
    <%= form.label :movement_date %>
    <%= form.date_select :movement_date %>
  </div>

  <div class="field">
    <%= form.label :value %>
    <%= form.number_field :value %>
  </div>
  
  <div class="field">
    <%= form.label :account_id %>
    <%= current_user.account.name %>
    <%= form.hidden_field :account_id, value: current_user.account.id%>
    <% form.select :account_id, options_for_select(Account.all.map {|account| [account.name, account.id]}, movement_account.account_destiny) %>
  </div>
  
  <% if movement_account.transfer? %>
    <div class="field">
      <%= form.label :account_destiny_id %>
      <%= form.select :account_destiny_id, options_for_select(Account.all.map {|account| [account.name, account.id]}, movement_account.account_destiny_id) %>
    </div>
  <% end %>  

  <div class="field">
    <%= form.label :movement_type %>
    <%= movement_account.movement_type %>
    <%= form.hidden_field :movement_type %>
    <% form.select :movement_type, options_for_select(MovementAccount.movement_types.map {|key, value| [key.titleize, MovementAccount.movement_types.key(value)]}, movement_account.movement_type) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

sys_bank/app/views/movement_accounts/edit.html.erb
<h1>Editing Movement Account</h1>

<%= render 'form', movement_account: @movement_account %>

<%= link_to 'Show', @movement_account %> |
<%= link_to 'Back', movement_accounts_path %>

sys_bank/app/views/movement_accounts/index.html.erb
<p id="notice"><%= notice %></p>
<div class="content">
  <div class="menu">
    <h1>Transactions</h1>
      <div class="flex">
        <div class="flex-container">
          <div><%= link_to 'Bank Draft', new_movement_account_path(movement_type: :bank_draft) %></div>
          <div><%= link_to 'Deposit', new_movement_account_path(movement_type: :deposit) %></div>
          <div><%= link_to 'Reversal', new_movement_account_path(movement_type: :reversal) %></div>
          <div><%= link_to 'Transfer', new_movement_account_path(movement_type: :transfer) %></div>
        </div>

        <div class="flex-container2">
          <table>
            <thead>
              <tr>
                <th>Account Origin</th>
                <th>Account Destiny</th>
                <th>Data</th>
                <th>Value</th>
                <th>Kind</th>
          <!--  <th>ID</th>
                <th>OTHER ID</th> -->
                <th colspan="3"></th>
              </tr>
            </thead>
            
            <tbody>
              <% @movement_accounts.each do |movement_account| %>
                <tr>
                  <td><%= movement_account.account.name %></td>
                  <td><%= movement_account.try(:account_destiny).try(:name) %></td>
                  <td><%= data_br(movement_account.movement_date) %></td>
                  <td><%= movement_account.format_value %></td>
                  <td><%= movement_account.movement_type.try(:humanize) %>
                  <td><% movement_account.account_id%>
                  <td><% movement_account.account_destiny_id%>
                  <td><% link_to 'Show', movement_account %></td>
                  <td><% link_to 'Destroy', movement_account, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
        
      </div>
    <br>
    <div class="link">
      <strong>Data:</strong> <%= data_br(Date.today) %>
      <%= link_to "Back", root_path %>
    </div>
  </div>
</div>

sys_bank/app/views/movement_accounts/new.html.erb
<div class="content">
  <div class="menu">
    <h1>Transactions</h1>

    <%= render 'form', movement_account: @movement_account %>
    <div class="link">
      <%= link_to 'Back', movement_accounts_path %>
    </div>
  </div>
</div>

sys_bank/app/views/movement_accounts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Movement date:</strong>
  <%= @movement_account.movement_date %>
</p>

<p>
  <strong>Value:</strong>
  <%= @movement_account.value %>
</p>

<%= link_to 'Edit', edit_movement_account_path(@movement_account) %> |
<%= link_to 'Back', movement_accounts_path %>